import localFont from "next/font/local";
import "./globals.css"; // Import global styles
import Navbar from "./components/Navbar"; // Import Navbar
import Footer from "./components/Footer"; // Import Footer

// Import your custom fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "notescope",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-color-mode="dark">
      <head>
        <title>notescope</title>
        <script
          src="https://kit.fontawesome.com/b6611a44e2.js"
          crossorigin="anonymous"
        ></script>{" "}
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Include the Navbar globally */}
        <Navbar />

        {/* Render the page content */}
        {children}

        {/* Include the Footer globally */}
        <Footer />
      </body>
    </html>
  );
}
